APACHE:
    VUE_PORT: 8002
    HTTPS_PORT: 8443
    HTTP_PORT: 80
    DJANGO_PORT: 8001
    APACHE_PATH: '/path/to/apache'
    VUE_PATH: '/path/to/vue'
    PYTHON_PATH: '/path/to/python'
    WSGI_PATH: '/path/to/django/django/wsgi.py'
    DAJNGO_PATH: '/path/to/django'
    APACHE_PROXY_SERVICE: 'my-apache-porxy'
    APACHE_DJANGO_SERVICE: 'my-apache-django'
    APACHE_VUE_SERVICE: 'my-apache-vue'

REDIS:
    REDIS_PORT: 8003
    REDIS_SERVICE: 'my-redis'

MYSQL:
    MYSQL_PORT: 8004
    MYSQL_SERVICE: 'my-mysql'

PGSQL:
    PGSQL_PORT: 8005
    PGSQL_SERVICE: 'my-pgsql'
